---
- name: Hosts
  hosts: all
  become: true
  gather_facts: true
  tasks:
   - name: Hosts file
     ansible.builtin.template:
        src: hosts.j2
        dest: /etc/myhosts
        force: true
     when: inventory_hostname in groups.dev