---
- name: Modify
  hosts: dev,test,prod
  become: true
  tasks:
     - name: Development
       ansible.builtin.copy:
          content: "{{ issue_cont }}"
          dest: /etc/issue
          force: true
          
