---
- name: Haproxy
  hosts: balancers,webservers
  become: true
  tasks:
      - name: Bal
        ansible.builtin.include_role:
           name: balancer
        when: inventory_hostname in groups.blanacer
- name: Phpinfo
  hosts: webservers
  become: true
  roles:
     - phpinfo