---
- name: Users 
  hosts: dev,test,prod
  become: true
  vars:
     grp_dev: opsdev
     grp_mgr: opsmgr
  vars_files:
     - locker.yml
     - user_list.yml
  tasks:
    - name: Block1
      block:
       - name: Create grp 
         ansible.builtin.group:
           name: "{{ grp_dev }}"
           state: present
       - name: Create user devp
         ansible.builtin.user:
            name: "{{ item.name }}"
            password: "{{ pw_developer | password_hash('sha512') }}"
            password_expire_max: '60'
            groups: "{{ grp_dev }}"
         loop: "{{ users }}"
         when: item.job == 'developer'
      when: inventory_hostname not in groups.prod
    - name: Block1
      block:
       - name: Create grp 
         ansible.builtin.group:
           name: "{{ grp_mgr }}"
           state: present
       - name: Create user devp
         ansible.builtin.user:
            name: "{{ item.name }}"
            password: "{{ pw_manager | password_hash('sha512') }}"
            password_expire_max: '60'
            groups: "{{ grp_mgr }}"
         loop: "{{ users }}"
         when: item.job == 'manager'
      when: inventory_hostname in groups.prod
