---
- name: YUM REPO
  hosts: all
  become: true
  tasks:
     - name: BaseOS
       ansible.builtin.yum_repository:
          name: "{{ item.name }}"
          description: "{{ item.description }}"
          baseurl: "{{ item.baseurl }}"
          enabled: yes
          gpgcheck: yes
          gpgkey: http://content/rhel9.0/x86_64/dvd/RPM-GPG-KEY-redhat-release
       loop: "{{ yum_repo }}"